### ISSUE TITLE
Alumniblogg och reseberättelser

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#1]
Fixa sidorna och snygga till det. Eventuellt med fina figurer, bilder och teckningar!

**Comment by CL-Webbunderhallare** [comment]
Alla sidor är finns behöver eventuellt stylas om.
Emelies bilder saknas.

**Comment by Webbutvecklare-CL** [comment]
pog! gj!!
