### ISSUE TITLE
Navbar: Renskriv koden

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#10]
Navbar funkar rätt okej, men koden är inte super lättläst. 

-Skriv om den så att framtida webb-folk kan sätta sig in i den utan att tappa håret. 
-Lägg även till kommentarer

-Undersök om man bör skippa att använda map() för att göra koden mer läslig för icke-dataloger.

**Comment by Webbutvecklare-CL** [comment]
låg prio, bör göras som tidigast efter lansering

**Comment by Gilvarig** [comment]
Skill issue

**Comment by rappos** [comment]
Var inne och kikade på den här igår. Alltså... Vet inte vad jag ska säga. Krävs en del arbete tror jag, men ska nog komma på nåt. Fick rätt snurr på huvudet
