### ISSUE TITLE
KPU på om oss

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#112]
På "Om oss" borde kanske KPU finnas med om vilka som är inkluderade i sektionen? Vet för lite för att skriva en text om dem själv

**Comment by eamkth** [comment]
Jag håller med. Även om det inte dyker upp så många från KPU i sektionssammanhang så borde de vara jämbördiga i texten på webben.

Mitt förslag skulle vara att ha ganska korta texter om utbildningarna och hänvisa till KTH för mer info. Nuvarande text som ChatGPT skrivit om inriktningarna är ärligt talat ganska kass.
