### ISSUE TITLE
Sångbokens tillbakaknapp

### ISSUE THREAD

**Issue by rappos** [Webbutvecklare-CL/cl-sektionen.se#117]
Tillbakaknappen på en sång leder till startsidan, inte sidan för sångboken. 
Windows 11, Edge webbläsare
![image](https://github.com/Webbutvecklare-CL/cl-sektionen.se/assets/6437769/61218883-3e8e-4401-9a29-846c36c9bf76)

**Comment by CL-Webbunderhallare** [comment]
Buggen fixade. Problem nu är att knappen kan i vissa fal leda en bort från webbsidan tillbaka till typ googles startsida, Facebook eller sidan man var in på tidigare.

**Comment by rappos** [comment]
Kan man inte ha en knapp som bara går "upp" ett steg? Vet inte vilka andra
ställen komponenten används, men tänker mig att det går att ha en modulär
knapp/annan knapp

Den lör 27 maj 2023 kl 01:27 skrev Jesper Svensson ***@***.***

**Comment by CL-Webbunderhallare** [comment]
Hänger inte riktigt med på vad du menar.
Lösningen nu är att den går ett steg tillbaka i historiken precis som om du tryckt på tillbaka knappen i webbläsaren förutom om du öppnat länken i en ny flik.

**Comment by rappos** [comment]
jag tycker inte att det är önskat beteende av en tillbakaknapp. den
funktionen finns redan som du säger i alla webbläsare. jag hade önskat att
knappen gick från:
"emil.se/a/b" till "emil.se/a", så att man kommer *upp *i trädet liksom.

Den lör 27 maj 2023 kl 17:25 skrev Jesper Svensson ***@***.***

**Comment by Gilvarig** [comment]
Jag tänker att det mest logiska är att knappen tar en tillbaka till sångboksidan.
så om man är på `/sangbok/porthos_visa` och trycker på tillbakaknappen så ska man kommer  till `/sangbok/` då det är med störst sannolikhet där användaren kommer ifrån
