### ISSUE TITLE
Menyerna borde stängas om man klicka utanför på mobilversion.

### ISSUE THREAD

**Issue by CL-Webbunderhallare** [Webbutvecklare-CL/cl-sektionen.se#15]
I mobilverionen: om man trycker på en meny i navbaren ex Studier så kan man inte stänga menyn igen genom att trycka på bakgrunden/utanför, vilket man borde kunna göra.

**Comment by Webbutvecklare-CL** [comment]
Färdigt, pushat till dev branch!
