### ISSUE TITLE
Error på inlogg på Personalrummet

### ISSUE THREAD

**Issue by Gilvarig** [Webbutvecklare-CL/cl-sektionen.se#152]
Har försökt att logga in på personalrummet för att göra ett inlägg men varje gång jag loggar in så får jag denna error!
Får errorn **Failed to load resource: net::ERR_BLOCKED_BY_CLIENT** men har inte blockat något så vidare jag vet

![image](https://github.com/Webbutvecklare-CL/cl-sektionen.se/assets/43792656/d01d5232-bf2c-420e-bc51-b34c2fe063b4)

**Comment by CL-Webbunderhallare** [comment]
Felet var att enskildaposter som försäljningsansvarig inte fanns med i all_committees eftersom de ligger under enskilda. Detta gjorde att när välkomsttexten i personalrummet skulle visas hittades inte forsaljningsansvarig.
Åtgärdade i 31e4cac genom att lägga till en lista med enskildaposter som lades in i all_committees.
