### ISSUE TITLE
Utseende på textsidor

### ISSUE THREAD

**Issue by CL-Webbunderhallare** [Webbutvecklare-CL/cl-sektionen.se#18]
Just nu har ex VFU och Illabehandling två olika utseende. En ligger på bakgrunden och en ligger som en artikel. Exprimentera och se vilken som fungerar bäst.

**Comment by CL-Webbunderhallare** [comment]
Jag kan tycka att artikelformatet är bra för att få det att stå ut lite mer och ger en bättre kontrast.

**Comment by Webbutvecklare-CL** [comment]
Mer generellt: 
Skapa riktlinjer över hur olika sidor egentligen ska se ut!

Ännu mer generellt:
Skapa riktlinjer över hur stylingen i allmänhet ska se ut, exempelvis ska vi ha rundade kanter? hur runda? Hur mycket box shadow? Vilken font ska vi ha egentligen?

**Comment by CL-Webbunderhallare** [comment]
Instämmer, kanske mindre viktigt nu. Kanske till och med bra att göra lite olika för att se vad som fungerar bäst.

**Comment by CL-Webbunderhallare** [comment]
Sidor med statisk text typ VFU och Illabehandling ska ligga platt på sidan som det redan gör på illabehandling.
Sidor som är skrivna av användare typ alumniblogg, reseberättelser och aktuellt sidan ska ha ett mer brev liknande utseende som det redan har idag.
