### ISSUE TITLE
Sångboken på hemsidan!!

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#2]
Lägga in sångboken (den nya) på hemsidan. Använd fysiks som inspo.

Obs (sångbokfolket har okejat. Det var alltid tanken.)

**Comment by Webbutvecklare-CL** [comment]
Lååååg prio, först efter att aktuellt fungerar.

En tanke är dock att detta lockar till användning av hemsidan, så kanske inte låg prio ändå.

**Comment by CL-Webbunderhallare** [comment]
Går det lägga in sångboken i Markdown???

**Comment by Webbutvecklare-CL** [comment]
> Går det lägga in sångboken i Markdown???

Ja, dock är min rädsla att det blir långsamt att ladda in från vad jag ser från markdownsidorna just nu. Vi vill iaf ha basically instant sökning (förhands-indexerad) och snabb laddning (dvs statiska sidor).

**Comment by CL-Webbunderhallare** [comment]
Yes men det går att fixa genom att skicka in filen som en serverside prop. Gällande indexeringen håller jag med.

**Comment by Webbutvecklare-CL** [comment]
https://drive.google.com/drive/folders/1UNPonk4-UJ9LH2bv12NJ09NKWcV8zP1v

**Comment by rappos** [comment]
Koden för datas sångbok: [GitHub](https://github.com/datasektionen/audio)
