### ISSUE TITLE
Hedersmedlemmar-sida

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#4]
Hedra hedersmedlemmar genom en sida dedikerat till dem. Med motiveringar, året de valdes in och en bild på dem.

**Comment by CL-Webbunderhallare** [comment]
Lägga till alla som har fått hedersodersmedalj?

**Comment by Webbutvecklare-CL** [comment]
> Lägga till alla som har fått hedersodersmedalj?

Ja, vi kan snacka med styrelsen om att sammanställa en lista!

**Comment by eamkth** [comment]
Förväxla inte hedersmedlemmar med hedersorden. Det är nästan som att säga att Java och JavaScript är samma sak. 😉

**Comment by eamkth** [comment]
> Det som saknas är: Årtal och motivering för Jan Scheffel och Hans Thunberg 

**Från SM 5 2013/2014, den 12 februari 2014:**
"Mötet beslutade
att enhälligt välja Jan Scheffel och Hans Thunberg till hedersmedlemmar i Sektionen för
Civilingenjör & Lärare (CL)."

**Från motionen inför detta SM:**
> ”Jan och Hans arbete för studenterna på programmet för Civilingenjör & Lärare började redan innan det ens fanns ett program. De var ansvariga för utvecklandet av programmet och arbetade tillsammans under programmets första 10 år som ProgramAnsvariga (PA). Som PA har de varit ansvariga för programmets övergripande utformning och kvalitet. I detta arbete har de många gånger stridit både med men även mot sektionen, men alltid med studenternas bästa i åtanke. Både Jan och Hans har nu avgått som PA och vi anser det därför lämpligt att sektionen tar upp frågan om att uppmärksamma dessa individer som kanske gjort mer för studenter på programmet för Civilingenjör & Lärare än någon annan. Både Hans och Jan fortsätter att introducera nya CL-studenter till KTH genom kurserna Ingenjörsvetenskap (som Jan hållit i sedan starten) och Perspektiv på matematik (som Hans håller i sedan ett par-tre år).”
> 
> Vi anser att även om dessa insatser varit riktade mot studenterna och programmet snarare än mot sektionen som sådan måste studenternas studier anses så nära kopplat till ”sektionens intressen och strävanden” att det är rimligt att anta att formuleringen i stadgan även är tänkt att täcka denna sorts insatser.

**Comment by CL-Webbunderhallare** [comment]
Fortfarande vissa visuella fel på mobilvyn.

**Comment by Webbutvecklare-CL** [comment]
nyfunnen styling-fel:
När fönstret är smalt kan motivering för hedersmedlemmar wrap:a ner bakom hedersorden!

**Comment by Webbutvecklare-CL** [comment]
@CL-Webbunderhallare denna verkar klar?

**Comment by CL-Webbunderhallare** [comment]
Utöver att det kanske finns fler namn och att vissa saknar efternamn osv. Men markerar issue som klar då det är tveksamt om informationen som behövs kommer dyka upp.
