### ISSUE TITLE
Aktuellt sidan

### ISSUE THREAD

**Issue by CL-Webbunderhallare** [Webbutvecklare-CL/cl-sektionen.se#50]
Visa en längre lista på aktuellt inlägg och events.

**Comment by Webbutvecklare-CL** [comment]
### Status:
V1
- [x] Alla inlägg kommer med
- [x] Responsiv filterpanel 
- [x] Sökfunktion
- [x] Filtrering på nyhet/event
- [x] Filtrering på kategori (tags)
- [x] Filtrering på publiceringsdatum
- [x] Sortering efter datum (trivialt uppfylld)
- [ ] Sortering efter nämnd/författare
- [ ] Sortering efter titel (alfabetisk)
- [ ] Stigande/fallande sortering

V2
- [ ] Meny för prenumeration/notiser
- [ ] Bättre system för att göra Queries, Känns som en waste att en revalidate ska göra en read på hela databasen eller att vi limitar till x antal senaste inlägg.
- [ ] Kategorier (tags) och typen av inlägg ska synas.
- [ ] Renskrivning av kod. Om sidan blir trög i samband med att antalet inlägg växer finns en stor prestanda vinst i att skriva om `.filter()` kedjan som en enda giga filter istället. Utöver det finns och koden i `useEffect()` för tags som är en eyesore och kan förenklas rejält.

**Comment by Webbutvecklare-CL** [comment]
V1 färdigt, återstående funktioner får bli egna issues
