### ISSUE TITLE
Tydligare skillnad på menyvalen verksamhet och organisation

### ISSUE THREAD

**Issue by CL-Webbunderhallare** [Webbutvecklare-CL/cl-sektionen.se#55]
Innehålls uppdelningen är bra, iaf inte det som åsyftas i denna issue. Men ordet verksamhet och organisation är väldigt lika i innebörd och det som ligger under organisation hade likväl kunnat vara under verksamhet. Därför kanske man kan ändra på någon eller båda för att göra det tydligare för användaren vad den kan tänkas finna under den menyn.
Ett kanske inte perfekt förslag är att byta namn på Verksamheten till På sektionen/Händer på sektionen.

**Comment by Webbutvecklare-CL** [comment]
Jag tänker att "verksamheten" är den menyn som gemene sektionsmedlem kommer att interagera med allra mest. Så Kanske det skulle passa med tex "för studenter"?

Alternativt kan "organisation" bytas ut med "sektionen"?

**Comment by CL-Webbunderhallare** [comment]
Jag gillar förstudenter men det blir lite oklart tillsammans med "Studier". Tycker att det "På gång", "Just nu" eller någon variant på det hade funkat bra. Tillsammans med det tycker jag att "Sektionen" passar bättre än "Organisationen".

**Comment by Webbutvecklare-CL** [comment]
Implementerade en mishmash av förslagen!
