### ISSUE TITLE
Hedersmedlemmar konstig på mobil

### ISSUE THREAD

**Issue by rappos** [Webbutvecklare-CL/cl-sektionen.se#58]
Första bilden vanlig mobilvy, andra är med "visa som desktop". 
Samsung galaxy s23 ultra. Microsoft Edge.

![Screenshot_20230325_221216_Edge.jpg](https://user-images.githubusercontent.com/6437769/227742262-3ce02190-6b7a-4a37-9f65-91661725bf63.jpg)

![Screenshot_20230325_221223_Edge.jpg](https://user-images.githubusercontent.com/6437769/227742263-9fdcb862-e774-4a0f-bcd9-246b8c702dff.jpg)

**Comment by CL-Webbunderhallare** [comment]
Det blev ett missöde med en merge... Fixas i en kommande PR
