### ISSUE TITLE
Framsida: "För företag"

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#7]
Lägg in en kort presentation om CL och kontaktinfo för intresserade företag på framsidan.

**Comment by CL-Webbunderhallare** [comment]
Ska vi ha det på framsidan om vi redan har en hel meny för "För Företag"?

**Comment by CL-Webbunderhallare** [comment]
Sidor och sektioner för det är skapat men texten på framsidan ska kanske ändras. Sidan /for-foretag behöver mer text och kanske en produktportfölj.
