### ISSUE TITLE
Quick nav

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#76]
För nuvarande svårt att se en hel sidas innehåll utan att faktiskt scrolla hela vägen. Vissa sidor, exempelvis "index" och "dokument" börjar bli lite längre nu och det som finns längre ner på dessa sidor upplevs lite begravda. Jag föreslår en mini nav som länkar till varje rubrik på sidan.

Spec/krav:
- [ ]  Ska synas för skärmstorlekar med bredd >1500px (eller annan godtycklig storlek)
- [ ] Ska gå att kollapsa
- [ ] Ska länka till rubriker på sidan med #
- [ ] Bör vara diskret och inte störande.
- [ ] Ska hämta samtliga headings (förslagsvis h1 & h2) på sidan.
- [ ] Ska även fungera på markdown sidor.

**Comment by CL-Webbunderhallare** [comment]
Idé är att kanske göra fler röda tabs som Om-oss taben på start

**Comment by CL-Webbunderhallare** [comment]
Sida som kan dra nytta av detta är "engagera dig"
