### ISSUE TITLE
Routing för 'förtroendevalda' sidan

### ISSUE THREAD

**Issue by Webbutvecklare-CL** [Webbutvecklare-CL/cl-sektionen.se#79]
Som det låter.
Man ska kunna skicka tex `https://cl-sektionen.vercel.app/fortroendevalda/Valberedningen` som en länk till någon och de ska inte behöva leta själva i menyn och trycka på rätt nämnd.

**Comment by CL-Webbunderhallare** [comment]
Fixat i 9dff34c. För att komma till en specifik nämnd kan man nu skriva https://cl-sektionen.vercel.app/fortroendevalda#valberedningen
