### ISSUE TITLE
Fulltextsökning i sånger

### ISSUE THREAD

**Issue by eamkth** [Webbutvecklare-CL/cl-sektionen.se#88]
Sångboken på webben blev väldigt bra. Jag testade sökningen och konstaterade att den bara söker i rubrikerna. Vore det möjligt att få till fulltextsökning? Det kan vara användbart både för att hitta rätt sånger till en gasque och för att snabbt hitta rätt sång när alla runtomkring en börjar sjunga utan att man uppfattat titeln.

**Comment by Webbutvecklare-CL** [comment]
Bortprioriterar detta för tillfället för att fokusera på lansering. Men detta kommer att läggas till så småningom. Troligtvis inför mottagningen

**Comment by Webbutvecklare-CL** [comment]
Lite work in progress men finns nu som alternativ i sökmenyn!
