### ISSUE TITLE
Reseberättelser från Afrika

### ISSUE THREAD

**Issue by eamkth** [Webbutvecklare-CL/cl-sektionen.se#99]
Såg att det saknades reseberättelser från Afrika och i nästa ögonblick hittade jag sådana från Veronica och Edith på https://www.kth.se/student/studier/utlandsstudier/studera-i-utveckling/fieldstudies/reseberattelser-fran-faltstudier-1.1188299. Det var kanske inte utbyte av den typ som de flesta åker på, men det vore väl ändå värt att höra med Veronica och Edith om det går bra att ha deras berättelser även på cl-sektionen.se?

**Comment by Webbutvecklare-CL** [comment]
Jag hör av mig och frågar om vi kan lägga upp dessa på hemsidan!
